/* Fixed NTRU+ parameter-set metadata. */
#include "ntruplus_local.h"

#define NTRUPLUS_768_N 768
#define NTRUPLUS_768_SECBITS 192
#define NTRUPLUS_768_SECURITY_CATEGORY 3
#define NTRUPLUS_768_PUBLIC_KEY_BYTES 1152
#define NTRUPLUS_768_PRIVATE_KEY_BYTES \
    ((2 * NTRUPLUS_768_PUBLIC_KEY_BYTES) + NTRUPLUS_KEY_HASH_BYTES)
#define NTRUPLUS_768_CIPHERTEXT_BYTES NTRUPLUS_768_PUBLIC_KEY_BYTES
#define NTRUPLUS_768_ENCAP_SEED_BYTES 96

#define NTRUPLUS_864_N 864
#define NTRUPLUS_864_SECBITS 216
#define NTRUPLUS_864_SECURITY_CATEGORY 3
#define NTRUPLUS_864_PUBLIC_KEY_BYTES 1296
#define NTRUPLUS_864_PRIVATE_KEY_BYTES \
    ((2 * NTRUPLUS_864_PUBLIC_KEY_BYTES) + NTRUPLUS_KEY_HASH_BYTES)
#define NTRUPLUS_864_CIPHERTEXT_BYTES NTRUPLUS_864_PUBLIC_KEY_BYTES
#define NTRUPLUS_864_ENCAP_SEED_BYTES 108

#define NTRUPLUS_1152_N 1152
#define NTRUPLUS_1152_SECBITS 256
#define NTRUPLUS_1152_SECURITY_CATEGORY 5
#define NTRUPLUS_1152_PUBLIC_KEY_BYTES 1728
#define NTRUPLUS_1152_PRIVATE_KEY_BYTES \
    ((2 * NTRUPLUS_1152_PUBLIC_KEY_BYTES) + NTRUPLUS_KEY_HASH_BYTES)
#define NTRUPLUS_1152_CIPHERTEXT_BYTES NTRUPLUS_1152_PUBLIC_KEY_BYTES
#define NTRUPLUS_1152_ENCAP_SEED_BYTES 144

#if NTRUPLUS_MAX_N != NTRUPLUS_1152_N
# error "NTRUPLUS_MAX_N must match the largest NTRU+ parameter set"
#endif
#if NTRUPLUS_MAX_ENCAP_SEED_BYTES != NTRUPLUS_1152_ENCAP_SEED_BYTES
# error "NTRUPLUS_MAX_ENCAP_SEED_BYTES must match the largest seed size"
#endif

static const NTRUPLUS_VINFO vinfo_map[NTRUPLUS_VINFO_COUNT] = {
    [EVP_PKEY_NTRUPLUS_768] = {
        "ntruplus768",
        NTRUPLUS_768_PRIVATE_KEY_BYTES,
        NTRUPLUS_768_PUBLIC_KEY_BYTES,
        NTRUPLUS_768_CIPHERTEXT_BYTES,
        NTRUPLUS_SHARED_SECRET_BYTES,
        NTRUPLUS_768_ENCAP_SEED_BYTES,
        EVP_PKEY_NTRUPLUS_768,
        NTRUPLUS_768_N,
        NTRUPLUS_768_SECBITS,
        NTRUPLUS_768_SECURITY_CATEGORY },
    [EVP_PKEY_NTRUPLUS_864] = {
        "ntruplus864",
        NTRUPLUS_864_PRIVATE_KEY_BYTES,
        NTRUPLUS_864_PUBLIC_KEY_BYTES,
        NTRUPLUS_864_CIPHERTEXT_BYTES,
        NTRUPLUS_SHARED_SECRET_BYTES,
        NTRUPLUS_864_ENCAP_SEED_BYTES,
        EVP_PKEY_NTRUPLUS_864,
        NTRUPLUS_864_N,
        NTRUPLUS_864_SECBITS,
        NTRUPLUS_864_SECURITY_CATEGORY },
    [EVP_PKEY_NTRUPLUS_1152] = {
        "ntruplus1152",
        NTRUPLUS_1152_PRIVATE_KEY_BYTES,
        NTRUPLUS_1152_PUBLIC_KEY_BYTES,
        NTRUPLUS_1152_CIPHERTEXT_BYTES,
        NTRUPLUS_SHARED_SECRET_BYTES,
        NTRUPLUS_1152_ENCAP_SEED_BYTES,
        EVP_PKEY_NTRUPLUS_1152,
        NTRUPLUS_1152_N,
        NTRUPLUS_1152_SECBITS,
        NTRUPLUS_1152_SECURITY_CATEGORY }
};

const NTRUPLUS_VINFO *ntruplus_get_vinfo(int evp_type)
{
    switch (evp_type) {
    case EVP_PKEY_NTRUPLUS_768:
        return &vinfo_map[EVP_PKEY_NTRUPLUS_768];
    case EVP_PKEY_NTRUPLUS_864:
        return &vinfo_map[EVP_PKEY_NTRUPLUS_864];
    case EVP_PKEY_NTRUPLUS_1152:
        return &vinfo_map[EVP_PKEY_NTRUPLUS_1152];
    }
    return NULL;
}
